# Queries generated automatically from db_prepare.py
dict_insert  = 'INSERT INTO components (`Part Number`, `Library Ref`, `Library Path`, `Comment`, `Component Kind`, `Component Type`, `Footprint`, `Pin Count`, `Case`, `Footprint Path`, `Footprint Ref`, `PackageDescription`, `Device`, `Mounted`, `Socket`, `SMD`, `Status`, `Color`, `Part Description`, `Manufacturer`, `Manufacturer Part Number`, `ComponentHeight`, `Manufacturer1 Example`, `Manufacturer1 Part Number`, `Manufacturer1 ComponentHeight`, `HelpURL`, `ComponentLink1URL`, `ComponentLink1Description`, `ComponentLink2URL`, `ComponentLink2Description`, `Author`, `CreateDate`, `LatestRevisionDate`, `Table`, `Sim Model Name`, `Sim File`, `Sim SubKind`, `Sim Netlist`, `Sim Spice Prefix`, `Sim Port Map`, `Resistanse`, `Value`, `TC`, `Power`, `Tolerance`, `Voltage`) VALUES (:Part_Number, :Library_Ref, :Library_Path, :Comment, :Component_Kind, :Component_Type, :Footprint, :Pin_Count, :Case, :Footprint_Path, :Footprint_Ref, :PackageDescription, :Device, :Mounted, :Socket, :SMD, :Status, :Color, :Part_Description, :Manufacturer, :Manufacturer_Part_Number, :ComponentHeight, :Manufacturer1_Example, :Manufacturer1_Part_Number, :Manufacturer1_ComponentHeight, :HelpURL, :ComponentLink1URL, :ComponentLink1Description, :ComponentLink2URL, :ComponentLink2Description, :Author, :CreateDate, :LatestRevisionDate, :Table, :Sim_Model_Name, :Sim_File, :Sim_SubKind, :Sim_Netlist, :Sim_Spice_Prefix, :Sim_Port_Map, :Resistanse, :Value, :TC, :Power, :Tolerance, :Voltage)'
tuple_insert = 'INSERT INTO components (`Part Number`, `Library Ref`, `Library Path`, `Comment`, `Component Kind`, `Component Type`, `Footprint`, `Pin Count`, `Case`, `Footprint Path`, `Footprint Ref`, `PackageDescription`, `Device`, `Mounted`, `Socket`, `SMD`, `Status`, `Color`, `Part Description`, `Manufacturer`, `Manufacturer Part Number`, `ComponentHeight`, `Manufacturer1 Example`, `Manufacturer1 Part Number`, `Manufacturer1 ComponentHeight`, `HelpURL`, `ComponentLink1URL`, `ComponentLink1Description`, `ComponentLink2URL`, `ComponentLink2Description`, `Author`, `CreateDate`, `LatestRevisionDate`, `Table`, `Sim Model Name`, `Sim File`, `Sim SubKind`, `Sim Netlist`, `Sim Spice Prefix`, `Sim Port Map`, `Resistanse`, `Value`, `TC`, `Power`, `Tolerance`, `Voltage`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'

colNames = ('Part Number', 
            'Library Ref', 
            'Library Path', 
            'Comment', 
            'Component Kind', 
            'Component Type', 
            'Footprint', 
            'Pin Count', 
            'Case', 
            'Footprint Path', 
            'Footprint Ref', 
            'PackageDescription', 
            'Device', 
            'Mounted', 
            'Socket', 
            'SMD', 
            'Status', 
            'Color', 
            'Part Description', 
            'Manufacturer', 
            'Manufacturer Part Number', 
            'ComponentHeight', 
            'Manufacturer1 Example', 
            'Manufacturer1 Part Number', 
            'Manufacturer1 ComponentHeight', 
            'HelpURL', 'ComponentLink1URL', 
            'ComponentLink1Description', 
            'ComponentLink2URL', 
            'ComponentLink2Description', 
            'Author', 
            'CreateDate', 
            'LatestRevisionDate', 
            'Table', 
            'Sim Model Name', 
            'Sim File', 
            'Sim SubKind', 
            'Sim Netlist', 
            'Sim Spice Prefix', 
            'Sim Port Map', 
            'Resistanse', 
            'Value', 
            'TC', 
            'Power', 
            'Tolerance', 
            'Voltage')